// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CleanDataset: typeof import('./src/components/user/CleanDataset.vue')['default']
    CompletenessCurves: typeof import('./src/components/admin/CompletenessCurves.vue')['default']
    DisplayExperiments: typeof import('./src/components/admin/DisplayExperiments.vue')['default']
    Filters: typeof import('./src/components/admin/Filters.vue')['default']
    GetPredictionForm: typeof import('./src/components/user/GetPredictionForm.vue')['default']
    LinePlot: typeof import('./src/components/LinePlot.vue')['default']
    Listbox: typeof import('@headlessui/vue')['Listbox']
    ListboxButton: typeof import('@headlessui/vue')['ListboxButton']
    ListboxOption: typeof import('@headlessui/vue')['ListboxOption']
    ListboxOptions: typeof import('@headlessui/vue')['ListboxOptions']
    ProcessData: typeof import('./src/components/admin/ProcessData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowData: typeof import('./src/components/user/ShowData.vue')['default']
    ShowPrediction: typeof import('./src/components/user/ShowPrediction.vue')['default']
    Switch: typeof import('@headlessui/vue')['Switch']
    VButton: typeof import('./src/components/VButton.vue')['default']
    VCheckbox: typeof import('./src/components/VCheckbox.vue')['default']
    VDangerAlert: typeof import('./src/components/VDangerAlert.vue')['default']
    VFileInput: typeof import('./src/components/VFileInput.vue')['default']
    VHeader: typeof import('./src/components/VHeader.vue')['default']
    VInfoAlert: typeof import('./src/components/VInfoAlert.vue')['default']
    VInput: typeof import('./src/components/VInput.vue')['default']
    VSelect: typeof import('./src/components/VSelect.vue')['default']
    VSeparator: typeof import('./src/components/VSeparator.vue')['default']
    VSwitch: typeof import('./src/components/VSwitch.vue')['default']
    VTitle: typeof import('./src/components/VTitle.vue')['default']
  }
}
